
import "./globals.css";
import Provider from "@/components/provider";
import {ImageKitProvider } from '@imagekit/next';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
      <ImageKitProvider urlEndpoint={process.env.NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}>
        <Provider>
        {children}
        </Provider>
      </ImageKitProvider>
      </body>
    </html>
  );
}
